version: "3"

volumes:
  postgres:
  prometheus_data: {}
services:
#  jakarta-movie:
#    build: .
#    ports:
#      - "9080:9080"
#      - "9443:9443"
#    network_mode: "host"
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: movies
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "15432:5432"
    networks:
      - env-network
  sonar:
    image: sonarqube
    container_name: sonar
    ports:
      - "9000:9000"
#  zipkin:
#    image: openzipkin/zipkin
#    ports:
#      - "9411:9411"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    network_mode: "host"
networks:
  env-network:
    driver: bridge